CREATE TABLE User(
    IDUser BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    GivenName VARCHAR(30) NOT NULL,
    FLastName VARCHAR(20) NOT NULL,
    MLastName VARCHAR(20),
    Username VARCHAR(20) NOT NULL UNIQUE,
    AccessKey CHAR(25) NOT NULL
);

CREATE TABLE Device(
    IDDevice BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    AccessKey CHAR(20) NOT NULL,
    Place VARCHAR(15) NOT NULL
);

CREATE TABLE User_Device(
    IDUser BIGINT NOT NULL,
    CONSTRAINT IDUser FOREIGN KEY (IDUser)
    REFERENCES User(IDUser),
    IDDevice BIGINT NOT NULL,
    CONSTRAINT IDDevice FOREIGN KEY (IDDevice)
    REFERENCES Device(IDDevice),
    PRIMARY KEY (IDUser, IDDevice)
);

CREATE TABLE Record(
    IDRecord BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ReadTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Temperature FLOAT DEFAULT 0,
    Humidity FLOAT DEFAULT 0,
    Ppm FLOAT DEFAULT 0,
    IDDevice BIGINT NOT NULL,
    FOREIGN KEY (IDDevice) REFERENCES Device(IDDevice)
);